import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, ShieldCheck, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { Link } from "wouter";

export default function Admin() {
  const { isAuthenticated } = useAuth();
  const utils = trpc.useUtils();
  const me = trpc.community.dashboard.useQuery(undefined, { enabled: isAuthenticated });
  const isAdmin = me.data?.currentRole === "admin";
  const users = trpc.admin.users.useQuery(undefined, { enabled: isAdmin });
  const bootstrap = trpc.admin.bootstrap.useMutation({ onSuccess: () => { toast.success("Administrator access activated. Reloading permissions."); utils.auth.me.invalidate(); utils.community.dashboard.invalidate(); }, onError: error => toast.error(error.message) });
  const updateRole = trpc.admin.updateUserRole.useMutation({ onSuccess: () => { toast.success("Role updated."); users.refetch(); }, onError: error => toast.error(error.message) });
  if (!isAuthenticated) return <main className="min-h-screen bg-[#f5f3eb] p-8"><div className="mx-auto max-w-lg rounded-[28px] bg-white p-8 text-center shadow-sm"><ShieldCheck className="mx-auto h-8 w-8 text-[#2d6a58]" /><h1 className="mt-4 font-[Fraunces] text-3xl font-semibold">Administrator access</h1><p className="mt-3 text-sm leading-6 text-[#64736c]">Sign in with the project-owner account to activate or manage PicklePlay administration.</p><Button onClick={startLogin} className="mt-6 rounded-full bg-[#19473e]">Sign in</Button></div></main>;
  return <main className="min-h-screen bg-[#f5f3eb] p-6 text-[#173d35] sm:p-10"><div className="mx-auto max-w-4xl"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-[#39705d]"><ArrowLeft className="h-4 w-4" /> Community home</Link><div className="mt-7 rounded-[30px] border border-[#dfe1d5] bg-[#fffef9] p-7"><div className="flex items-start gap-4"><div className="rounded-2xl bg-[#e5efe3] p-3 text-[#2f6f5c]"><ShieldCheck className="h-7 w-7" /></div><div><p className="text-[11px] font-extrabold uppercase tracking-[.14em] text-[#668176]">Platform governance</p><h1 className="mt-1 font-[Fraunces] text-4xl font-semibold tracking-[-.05em]">Administrator console</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#66756c]">Only the project-owner identity can activate the first administrator. Active administrators can then assign player, organizer, moderator, or administrator roles.</p></div></div>{!isAdmin ? <div className="mt-7 rounded-2xl bg-[#f3f4ed] p-5"><p className="text-sm leading-6 text-[#5c6b63]">If you are the project owner, use this one-time bootstrap action. Other signed-in users are denied by the server.</p><Button onClick={() => bootstrap.mutate()} disabled={bootstrap.isPending} className="mt-4 rounded-full bg-[#19473e]">Activate project administrator</Button></div> : <div className="mt-7"><div className="flex items-center gap-2"><UsersRound className="h-5 w-5 text-[#39705d]" /><h2 className="font-[Fraunces] text-2xl font-semibold">Community accounts</h2></div><div className="mt-4 overflow-hidden rounded-2xl border border-[#e0e3d9]">{users.data?.map(account => <div key={account.id} className="flex flex-col gap-3 border-b border-[#e9ebe4] p-4 last:border-b-0 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold">{account.displayName || account.name || "Unnamed member"}</p><p className="mt-1 text-xs text-[#69776e]">{account.email || account.city || "No public profile detail"}</p></div><select value={account.role} onChange={event => updateRole.mutate({ userId: account.id, role: event.target.value as "player" | "organizer" | "moderator" | "admin" })} disabled={updateRole.isPending} className="rounded-full border border-[#d9ddd2] bg-white px-3 py-2 text-sm font-bold text-[#355f52]"><option value="player">Player</option><option value="organizer">Organizer</option><option value="moderator">Moderator</option><option value="admin">Administrator</option></select></div>) || <p className="p-5 text-sm text-[#69776e]">Loading accounts…</p>}</div></div>}</div></div></main>;
}
