import { useAuth } from "@/_core/hooks/useAuth";
import { usePageTitle } from "@/hooks/usePageTitle";
import { startLogin } from "@/const";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, BellRing, MailX, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { Link } from "wouter";

export default function NotificationSettings() {
  const { isAuthenticated } = useAuth();
  usePageTitle("Notification settings");
  const preferences = trpc.community.notificationPreferences.useQuery(undefined, { enabled: isAuthenticated });
  const update = trpc.community.updateNotificationPreferences.useMutation({ onSuccess: () => { toast.success("Notification preferences saved."); preferences.refetch(); }, onError: error => toast.error(error.message) });
  const setPreference = (change: Partial<{ inAppEnabled: boolean; gameUpdatesEnabled: boolean; waitlistUpdatesEnabled: boolean }>) => {
    if (!preferences.data) return;
    update.mutate({ inAppEnabled: preferences.data.inAppEnabled, emailEnabled: false, gameUpdatesEnabled: preferences.data.gameUpdatesEnabled, waitlistUpdatesEnabled: preferences.data.waitlistUpdatesEnabled, ...change });
  };
  if (!isAuthenticated) return <main className="min-h-screen bg-[#f5f3eb] p-8"><div className="mx-auto max-w-lg rounded-[28px] bg-white p-8 text-center shadow-sm"><BellRing className="mx-auto h-8 w-8 text-[#2d6a58]" /><h1 className="mt-4 font-[Fraunces] text-3xl font-semibold">Notification settings</h1><p className="mt-3 text-sm leading-6 text-[#64736c]">Sign in to choose which in-app coordination updates appear in your PicklePlay account.</p><Button onClick={startLogin} className="mt-6 rounded-full bg-[#19473e]">Sign in</Button></div></main>;
  const preferenceRows = preferences.data ? [{ key: "inAppEnabled", title: "In-app notifications", description: "Show coordination updates in your PicklePlay notification center." }, { key: "gameUpdatesEnabled", title: "Organizer updates", description: "Receive updates from organizers for games you joined or are waiting for." }, { key: "waitlistUpdatesEnabled", title: "Waitlist changes", description: "Receive confirmation and promotion updates for your RSVP status." }] as const : [];
  return <main className="min-h-screen bg-[#f5f3eb] p-6 text-[#173d35] sm:p-10"><div className="mx-auto max-w-3xl"><Link href="/?view=profile" className="inline-flex items-center gap-2 text-sm font-bold text-[#39705d]"><ArrowLeft className="h-4 w-4" /> Player profile</Link><header className="mt-7 rounded-[30px] border border-[#dfe1d5] bg-[#fffef9] p-7"><div className="flex items-start gap-4"><div className="rounded-2xl bg-[#e5efe3] p-3 text-[#2f6f5c]"><BellRing className="h-7 w-7" /></div><div><p className="text-[11px] font-extrabold uppercase tracking-[.14em] text-[#55685e]">Personal settings</p><h1 className="mt-1 font-[Fraunces] text-4xl font-semibold tracking-[-.05em]">Choose your in-app updates.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#66756c]">These settings apply to the PicklePlay notification center. They do not affect attendance records or required safety actions.</p></div></div></header><section className="mt-6 overflow-hidden rounded-3xl border border-[#dfe1d5] bg-white">{preferences.isLoading ? <p className="p-6 text-sm text-[#66756c]">Loading your preferences…</p> : preferenceRows.map(row => <div key={row.key} className="flex items-start justify-between gap-5 border-b border-[#e6e8df] p-5 last:border-b-0"><div><h2 className="font-[Fraunces] text-2xl font-semibold">{row.title}</h2><p className="mt-1 max-w-xl text-sm leading-6 text-[#66756c]">{row.description}</p></div><Switch checked={Boolean(preferences.data?.[row.key])} onCheckedChange={checked => setPreference({ [row.key]: checked } as Partial<{ inAppEnabled: boolean; gameUpdatesEnabled: boolean; waitlistUpdatesEnabled: boolean }>)} disabled={update.isPending} aria-label={row.title} /></div>)}</section><section className="mt-6 rounded-3xl border border-[#eadfba] bg-[#fff8e5] p-5"><div className="flex gap-3"><MailX className="mt-0.5 h-5 w-5 shrink-0 text-[#a67835]" /><div><h2 className="font-[Fraunces] text-xl font-semibold">Email is not enabled</h2><p className="mt-1 text-sm leading-6 text-[#695c40]">PicklePlay currently uses only in-app coordination notifications. Email remains disabled until a separate provider, domain, and opt-in workflow are approved.</p></div></div></section><section className="mt-6 rounded-3xl bg-[#e6efe2] p-5"><div className="flex gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-[#39705d]" /><p className="text-sm leading-6 text-[#536b5f]">Notification delivery records are retained for operational reliability. No marketing or unsolicited email channel is activated by these controls.</p></div></section></div></main>;
}
